# Generated by Django 2.0.3 on 2018-03-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotasCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('data', models.DateTimeField(blank=True)),
                ('descricao', models.CharField(max_length=70)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('imagem', models.FileField(blank=True, upload_to='imagens_compras')),
                ('imagem1', models.FileField(blank=True, upload_to='imagens_compras')),
                ('tipo_gasto', models.CharField(choices=[('Serviços', 'SERVIÇOS'), ('Ferramentas', 'FERRAMENTAS')], max_length=10)),
            ],
        ),
    ]
