# Generated by Django 2.0.3 on 2018-03-16 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notascompra',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='notascompra',
            name='imagem1',
        ),
    ]
