# Generated by Django 2.0.3 on 2018-03-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_auto_20180318_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='imagem',
            field=models.FileField(blank=True, upload_to='imagens_compras'),
        ),
        migrations.AddField(
            model_name='nota',
            name='imagem1',
            field=models.FileField(blank=True, upload_to='imagens_compras'),
        ),
    ]
