# Generated by Django 2.0.3 on 2018-03-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_auto_20180318_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('query', models.CharField(max_length=150)),
                ('alias', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo_gasto',
            field=models.CharField(choices=[('Serviços', 'SERVIÇOS'), ('Ferramentas', 'FERRAMENTAS')], max_length=12),
        ),
    ]
