# Generated by Django 2.0.3 on 2018-03-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_auto_20180325_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='imagem',
            field=models.FileField(blank=True, upload_to='notas_compras'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='imagem1',
            field=models.FileField(blank=True, upload_to='notas_compras'),
        ),
    ]
